# Generated by Django 5.0.1 on 2024-02-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0003_tags_apostila_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostila',
            name='avaliacao',
            field=models.IntegerField(choices=[(5, 'Muito Bom'), (4, 'Bom'), (3, 'Regular'), (2, 'Ruim'), (1, 'Muito Ruim')], default=5),
        ),
    ]
