# Generated by Django 5.0.1 on 2024-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0004_apostila_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
