# Generated by Django 5.0.1 on 2024-02-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0007_alter_apostila_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostila',
            name='avaliacao',
            field=models.CharField(choices=[('5', 'Muito Bom'), ('4', 'Bom'), ('3', 'Regular'), ('2', 'Ruim'), ('1', 'Muito Ruim')], default='5', max_length=1),
        ),
    ]
